theme: jekyll-theme-slate
title: Cosi166B PlantClinique App
description: Eric Rosenheim (ericrosenheim@brandeis.edu), Osamah Mandawi (oamandawi@brandeis.edu), Roman Nguyen (taromka21@brandeis.edu), Prabu Gugagantha (prabug@brandeis.edu)